[package]
name = "framework-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
framework-datetime = { path = "../framework-datetime" }

anyhow.workspace = true
log.workspace = true