[package]
name = "framework-datetime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[features]
default = []
ntp = ["dep:rsntp"]
tokio = ["ntp", "dep:tokio", "rsntp/async"]

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
rsntp = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
web-time = "1.1"
