[package]
name = "framework-datetime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[features]
default = []
ntp = ["dep:rsntp"]
tokio = ["ntp", "dep:tokio", "rsntp/async"]

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
rsntp = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
