[package]
name = "framework-proc-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[features]
default = []
collect = ["dep:inventory"]

[dependencies]
inventory = { workspace = true, optional = true }
specta.workspace = true
specta-typescript.workspace = true
specta-serde.workspace = true
serde_json.workspace = true
serde.workspace = true
